<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import http, { unwrapResult } from '../api/client'
import { AdminApiError, type ApiResult } from '../api/result'
import AsyncState from '../components/AsyncState.vue'

interface Audit { id:number; domain:string; resourceId?:number; changeId?:number; operation:string; operatorId:string; operatorName?:string; requestId?:string; clientIp?:string; result:string; detailSummary?:string; errorCode?:string; errorMessage?:string; operatedAt:string }
interface Page<T>{items:T[];total:number;offset:number;limit:number}
const audits=ref<Audit[]>([]);const total=ref(0);const loading=ref(true);const error=ref<AdminApiError|null>(null);const detail=ref<Audit|null>(null);const detailOpen=ref(false);const filters=reactive({domain:undefined as string|undefined,operation:'',operatorId:'',result:undefined as string|undefined,offset:0,limit:20});
const columns=[{title:'时间',dataIndex:'operatedAt',key:'operatedAt',width:180},{title:'域',dataIndex:'domain',key:'domain',width:110},{title:'动作',dataIndex:'operation',key:'operation'},{title:'对象',key:'object'},{title:'操作人',dataIndex:'operatorName',key:'operatorName'},{title:'结果',dataIndex:'result',key:'result',width:100},{title:'Request ID',dataIndex:'requestId',key:'requestId'},{title:'操作',key:'action',width:80}]
async function load(){loading.value=true;error.value=null;try{const response=await http.get<ApiResult<Page<Audit>>>('/admin/audits/page',{params:filters});const page=unwrapResult(response.data);audits.value=page.items;total.value=page.total}catch(caught){error.value=caught instanceof AdminApiError?caught:null}finally{loading.value=false}}
async function openDetail(id:number){const response=await http.get<ApiResult<Audit>>(`/admin/audits/${id}`);detail.value=unwrapResult(response.data);detailOpen.value=true}
function changePage(page:number,pageSize:number){filters.offset=(page-1)*pageSize;filters.limit=pageSize;void load()}
onMounted(load)
</script>

<template><section class="workspace-page"><header class="page-heading"><div><p class="eyebrow">AUDIT TRAIL</p><h1>审计追踪</h1><p>按对象、动作、结果和时间追踪治理操作。</p></div><a-button @click="load">刷新</a-button></header><div class="workspace-panel audit-panel"><div class="filters"><a-select v-model:value="filters.domain" allow-clear placeholder="治理域" :options="['SERVICES','GATEWAY','TRAFFIC','ACCESS','CLIENTS','CHANGES'].map(value=>({value}))"/><a-input v-model:value="filters.operation" placeholder="操作类型"/><a-input v-model:value="filters.operatorId" placeholder="操作人"/><a-select v-model:value="filters.result" allow-clear placeholder="结果" :options="['SUCCESS','FAILED'].map(value=>({value}))"/><a-button type="primary" @click="filters.offset=0;load()">查询</a-button></div><AsyncState :loading="loading" :empty="!error&&audits.length===0" :dependency-unavailable="error?.category==='DEPENDENCY'" :forbidden="error?.category==='PERMISSION'" :title="error?.message"><a-table :columns="columns" :data-source="audits" row-key="id" size="middle" :pagination="{total,current:filters.offset/filters.limit+1,pageSize:filters.limit,showSizeChanger:true}" @change="(pagination:any)=>changePage(pagination.current,pagination.pageSize)"><template #bodyCell="{column,record}"><template v-if="column.key==='object'"><span>R{{record.resourceId||'-'}} / C{{record.changeId||'-'}}</span></template><template v-else-if="column.key==='result'"><a-tag :color="record.result==='SUCCESS'?'green':'red'">{{record.result}}</a-tag></template><template v-else-if="column.key==='action'"><a-button type="link" size="small" @click="openDetail(record.id)">详情</a-button></template></template></a-table></AsyncState></div><a-drawer v-model:open="detailOpen" title="审计详情" width="560"><a-descriptions v-if="detail" :column="1" bordered size="small"><a-descriptions-item label="Request ID">{{detail.requestId||'-'}}</a-descriptions-item><a-descriptions-item label="治理域 / 动作">{{detail.domain}} / {{detail.operation}}</a-descriptions-item><a-descriptions-item label="资源 / 变更">{{detail.resourceId||'-'}} / {{detail.changeId||'-'}}</a-descriptions-item><a-descriptions-item label="操作人">{{detail.operatorName||detail.operatorId}}</a-descriptions-item><a-descriptions-item label="结果">{{detail.result}}</a-descriptions-item><a-descriptions-item label="摘要">{{detail.detailSummary||'-'}}</a-descriptions-item><a-descriptions-item label="错误">{{detail.errorCode||'-'}} {{detail.errorMessage||''}}</a-descriptions-item><a-descriptions-item label="时间">{{detail.operatedAt}}</a-descriptions-item></a-descriptions></a-drawer></section></template>

<style scoped>.audit-panel{padding:0}.filters{display:grid;grid-template-columns:180px 1fr 1fr 160px auto;gap:12px;padding:16px;border-bottom:1px solid #eaecf0}</style>
