<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fons.cloud</groupId>
        <artifactId>fons4cloud-infrastructure</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <description>基础设施服务</description>
    <artifactId>fons4cloud-infrastructure-service</artifactId>

    <dependencies>
        <!-- api -->
        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-infrastructure-api</artifactId>
            <version>${infrastructure.api.version}</version>
        </dependency>

        <!-- nacos -->
        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-nacos-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- dubbo -->
        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-dubbo-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- cache -->
        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-common-cache</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>


    <build>
        <finalName>infrastructure-service</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven.jar.plugin.version}</version>
                <configuration>
                    <classesDirectory>target/classes/</classesDirectory>
                    <archive>
                        <manifest>
                            <mainClass>com.fons.cloud.infrastructure.Main</mainClass>
                            <!-- 打包时 MANIFEST.MF文件不记录的时间戳版本 -->
                            <useUniqueVersions>false</useUniqueVersions>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <classpathLayoutType>simple</classpathLayoutType>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <type>jar</type>
                            <includeTypes>jar</includeTypes>
                            <outputDirectory>
                                ${project.build.directory}/lib
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>